### ISSUE TITLE
command list support

### ISSUE THREAD

**Issue by matthewleon** [vimus/libmpd-haskell#100]
https://www.musicpd.org/doc/protocol/command_lists.html

Something to consider if the API will already undergo a potential breaking change.

**Comment by joachifm** [comment]
The [applicative command interface](https://github.com/vimus/libmpd-haskell/blob/master/src/Network/MPD/Applicative/Internal.hs#L14) does this. Or do you have something else in mind?

**Comment by matthewleon** [comment]
I missed that. Thanks.
