### ISSUE TITLE
Master seems to be broken and New release request for GHC-8.6

### ISSUE THREAD

**Issue by psibi** [vimus/libmpd-haskell#110]
The master seems to be broken for ghc-8.6:

https://travis-ci.org/vimus/libmpd-haskell/jobs/441594094#L2052

Also, would love to get a new release as `xmonad-extras` is dependent on it.

**Comment by joachifm** [comment]
I have uploaded a new version to hackage which includes GHC 8.6 support

The error you linked appears to be https://github.com/vimus/libmpd-haskell/issues/104 which is unrelated to GHC, I have just not found sufficient motivation to work on that one yet, sorry.
