### ISSUE TITLE
libmpd seems to have bitrotted

### ISSUE THREAD

**Issue by cbrt-x** [vimus/libmpd-haskell#140]
There seem to be a few issues when trying to build libmpd.
Most notably, `Control.Monad.Except` stopped re-exporting `Control.Monad` causing this package to not build anymore. 

I'll provide a patch to catch up on some issues, but I was wondering whether anyone still maintains this package. I'd like to rely on this and would be willing to help out with it.

**Comment by cbrt-x** [comment]
@joachifm

**Comment by joachifm** [comment]
@cbrt-x I have very little time these days, unfortunately.  I'd be happy to add you as a collaborator to the project, if you are interested in working on it.

**Comment by joachifm** [comment]
> @cbrt-x I have very little time these days, unfortunately. I'd be happy to add you as a collaborator to the project, if you are interested in working on it.

I have sent you an invite. Feel free to ping me if you need any input and I'll reply if I can, but I am unlikely to contribute much beyond that in the near term.

**Comment by cbrt-x** [comment]
Thank you @joachifm, I'll reach out in case I need anything
