### ISSUE TITLE
Upload fixed build to hackage

### ISSUE THREAD

**Issue by cbrt-x** [vimus/libmpd-haskell#142]
The version currently on hackage (10.0.0) does not currently build.
The fixed version should be uploaded (presumably under 10.0.1)

I have no experience with hackage but would be willing to do this task if I had the rights for it.

@joachifm (if you don't have time currently, don't feel pressured to do anything immediately)

**Comment by joachifm** [comment]
> The version currently on hackage (10.0.0) does not currently build. The fixed version should be uploaded (presumably under 10.0.1)
> 
> I have no experience with hackage but would be willing to do this task if I had the rights for it.

I can add your Hackage user to the list of package maintainers

**Comment by cbrt-x** [comment]
My hackage username is Jade512

**Comment by joachifm** [comment]
> My hackage username is Jade512

I have added you to the list of package maintainers

**Comment by joachifm** [comment]
Might make sense to look into using something like https://github.com/haskell-actions/hackage-publish to automate this.  More convenient and also more transparent than uploading random artifacts.

**Comment by cbrt-x** [comment]
@joachifm `cabal check` is complaining about the `-Wall` and `-Werror` not being portable `cpp-options`.
Is there a specific rationale for passing them or can I safely remove them? I'm not really sure what warnings you'd get from the C-compiler anyways.

**Comment by joachifm** [comment]
If I remember correctly, we rely on the C pre-processor to conditionally expose some internals when building the test-suite.

I don't know why -Wall and -Werror flags were added to cpp-options, but I expect that removing them should be okay.

**Comment by cbrt-x** [comment]
libmpd 0.10.0.1 has been released
