### ISSUE TITLE
Unexpected key-value pair error

### ISSUE THREAD

**Issue by TheLinuxKitten** [vimus/libmpd-haskell#89]
When executing **vimus**, it shows the following list in the *Playlist* and *Library* screens:
```
(none) - (none) - (none) - (none)
(none) - (none) - (none) - (none)
(none) - (none) - (none) - (none)
.....
```
The lists can be scrolled with PgUp and PgDown
In the *Library* screen, pressing **enter** on the first line **vimus** produces the following error and terminates:
```
vimus: MPD returned an unexpected response: unexpected key-value pair: ("duration", "119.779")

This is most likely a bug in libmpd! Please report it here:

https://github.com/vimus/libmpd-haskell/issues/new
```
And **MPD** starts playing music.

I'm using **MPD 0.20.0** from git.

Thanks

**Comment by joachifm** [comment]
Thank you for the report. I will look into this over the weekend.

**Comment by joachifm** [comment]
This was fixed in 46a2ff5f06b0b716b555e99e693dda86f73a74a0
I have backported that patch to libmpd 0.9 and uploaded a new point release to Hackage. Please let me know if the problem persists.

**Comment by TheLinuxKitten** [comment]
The problem still persists. It shows the same message.

**Comment by joachifm** [comment]
Ah, I see why. The parser fails because of the fractional value.

**Comment by joachifm** [comment]
I have uploaded another point release to Hackage.

**Comment by TheLinuxKitten** [comment]
It works ok.
