### ISSUE TITLE
Please support for recent versions of 'time'

### ISSUE THREAD

**Issue by peti** [vimus/libmpd-haskell#92]
GHC 8.0.1 cannot compile the current release of this library: http://packdeps.haskellers.com/feed?needle=libmpd.

**Comment by joachifm** [comment]
I hope to get around to doing this sometime later this week.

**Comment by MichielDerhaeg** [comment]
just changing the dependency version in the cabal file seems to work without issues.
``(time >= 1.5 && <1.6) -> (time >= 1.5 && <1.7)``

**Comment by joachifm** [comment]
I'd forgotten to push the patch ... pushed now. I'll close this once I've managed to get the archive onto Hackage. Thank you!

**Comment by MichielDerhaeg** [comment]
Hey, it's been a while since you have fixed this issue, it would be nice if you uploaded the new version to hackage :)

**Comment by joachifm** [comment]
@MichielDerhaeg ah, yes, completely forgot about this. I will be semi afk for a while so I can't do it until at least next week. Sorry for the delay.

**Comment by joachifm** [comment]
I have finally been able to upload a new point release to Hackage. Thank you for raising the issue and reminding me about it.
