### ISSUE TITLE
Repository is out of Sync with Hackage

### ISSUE THREAD

**Issue by psibi** [vimus/libmpd-haskell#94]
Background: `xmonad-extras` doesn't compile with `ghc-8.2` as `libmpd` build fails, so I wanted to send a PR to this repo to fix this.

But If I see the [cabal file](https://github.com/vimus/libmpd-haskell/blob/ea417b1dc4b917a43cd2cef671bac8372f69b3ee/libmpd.cabal#L2) here, the latest version according to it seems to be `0.9.0.1`. But If I go and see it's [hackage page](https://hackage.haskell.org/package/libmpd-0.9.0.6), the version according to it is `0.9.0.6`. 

So why is the cabal file outdated and the repository out of sync ?

**Comment by joachifm** [comment]
The hackage releases are based on https://github.com/vimus/libmpd-haskell/commits/libmpd-0.9. I'll upload a new version soonish. Sorry for the inconvenience.

**Comment by psibi** [comment]
Ah, I see. I have sent a relevant PR to that branch fixing the Stackage issue: https://github.com/vimus/libmpd-haskell/pull/95

It would be informative if the branch thing can be mentioned in `README.md`. Would be glad to see a new version of `libmpd`. I have already bumped the package version in the PR.

**Comment by joachifm** [comment]
Fixes are still intended to go into master first.  I'll consider adding a note about the stable branch at some point.
